name: shopping_list_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

assets:
  - .env

dependencies:
  common:
    path: ../common
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  dotenv: ^4.2.0
  logger: ^2.0.2+1
  postgres: ^3.0.5
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  flutter_lints: ^3.0.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
